# Blog settings
permalink: /log/:title


# My variables
name: Macleod Sawyer
description: I am an internet activist, developer, robot, inventor, and entrepreneur. I was built not born
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
